[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[dev]
  command = "npm run dev"
  port = 3000
  targetPort = 5173
  publish = "dist"
  autoLaunch = true
  framework = "#custom"

[[redirects]]
  from = "/blog/*"
  to = "/.netlify/functions/og-image-generator"
  status = 200

[[redirects]]
  from = "/property/*"
  to = "/.netlify/functions/og-image-generator"
  status = 200

[[redirects]]
  from = "/airbnb"
  to = "/.netlify/functions/og-image-generator"
  status = 200

[[redirects]]
  from = "/for-sale"
  to = "/.netlify/functions/og-image-generator"
  status = 200

[[redirects]]
  from = "/about"
  to = "/.netlify/functions/og-image-generator"
  status = 200

[[redirects]]
  from = "/blog"
  to = "/.netlify/functions/og-image-generator"
  status = 200

[[redirects]]
  from = "/contact"
  to = "/.netlify/functions/og-image-generator"
  status = 200

[[redirects]]
  from = "/guest-help"
  to = "/.netlify/functions/og-image-generator"
  status = 200

[[redirects]]
  from = "/vacation-rental-management"
  to = "/.netlify/functions/og-image-generator"
  status = 200

[[redirects]]
  from = "/payment"
  to = "/.netlify/functions/og-image-generator"
  status = 200

[[redirects]]
  from = "/payment-success"
  to = "/.netlify/functions/og-image-generator"
  status = 200

[[redirects]]
  from = "/privacy-policy"
  to = "/.netlify/functions/og-image-generator"
  status = 200

[[redirects]]
  from = "/we-do-better"
  to = "/.netlify/functions/og-image-generator"
  status = 200

[[redirects]]
  from = "/favorites"
  to = "/.netlify/functions/og-image-generator"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "max-age=0, no-cache, no-store, must-revalidate"
    Pragma = "no-cache"

# Function caching configuration
[functions.og-image-generator]
  included_files = []
  node_bundler = "esbuild"
  [functions.og-image-generator.environment]
    NODE_OPTIONS = "--max-old-space-size=256"
  [functions.og-image-generator.edge_functions]
    cache = "manual"
